// <auto-generated />
using System;
using BlazorServerDataAccessSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorServerDataAccessSample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20220225062210_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorServerDataAccessSample.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDay = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MailAddress = "yamada@mail.com",
                            UserName = "山田太郎"
                        },
                        new
                        {
                            UserId = 2,
                            BirthDay = new DateTime(2009, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MailAddress = "takanashi@mail.com",
                            UserName = "小鳥遊咲"
                        },
                        new
                        {
                            UserId = 3,
                            BirthDay = new DateTime(2004, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MailAddress = "anri@mail.com",
                            UserName = "山本杏里"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
